### PR TITLE
Add serialize and toJSON

### LINKED ISSUE #4: Add serialize and toJSON
https://github.com/AmpersandJS/ampersand-subcollection/issues/9

### PR DESCRIPTION
**Pull request by wraithgar**
child of https://github.com/AmpersandJS/ampersand-paginated-subcollection/pull/6
closes #4

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by kamilogorek** [comment]
Added tests are duplicated.

**Comment by wraithgar** [comment]
oops, must have pasted twice.  fixed.

**Comment by kamilogorek** [comment]
Perfect, +1 :)

**Comment by wraithgar** [comment]
published as `v2.0.0`

**Pull request merged**
